server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${douyin.datasource.driver-class-name}
    url: jdbc:mysql://${douyin.datasource.host}:${douyin.datasource.port}/${douyin.datasource.database}
    username: ${douyin.datasource.username}
    password: ${douyin.datasource.password}
  servlet:
      multipart:
        max-file-size: 10MB # 修改默认单个文件的最大上传限制
        max-request-size: 100MB # 修改默认单个请求的最大上传限制
  output:
    ansi:
      enabled: always # SpringBoot配置控制台彩色日志输出
  data:    
    redis:    
      host: ${douyin.redis.host}
      port: ${douyin.redis.port}
      password: ${douyin.redis.password}
      database: ${douyin.redis.database}
  cache:
    type: redis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.leechee.entity
  configuration:
    map-underscore-to-camel-case: false # 关闭mybatis的驼峰命名自动映射开关

douyin:
  jwt:
    secret-key: ${douyin.jwt.secret-key}
    ttl: 7200000
    token-name: token
  qiniuoss:
    bucket-name: ${douyin.qiniu.bucket-name}
    access-key: ${douyin.qiniu.access-key}
    secret-key: ${douyin.qiniu.secret-key}
    domain: ${douyin.qiniu.domain}
  default:
    avatar: ${douyin.default.avatar}
    background-image: ${douyin.default.background-image}